apiVersion: v1
kind: PersistentVolume
matadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: FileSystem
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /data
    type: DirectoryOrCreate